### ISSUE TITLE
Consider changing the project name

### ISSUE THREAD

**Issue by dergigi** [bitcoinppl/cove#1]
"Simple Bitcoin Wallet" (aka SBW) already exists. Having two projects with the same name is VERY confusing. Please _**strongly**_ consider changing the name. 

- Code: [btcontract/wallet](https://github.com/btcontract/wallet)
- [Screenshots](https://www.appbrain.com/app/sbw-simple-bitcoin-wallet/com.btcontract.wallet)
- Website: https://sbw.app/

**Comment by nvk** [comment]
Always has new name, just not public yet.

**Comment by nvk** [comment]
Actually already public "Cove" :)
