### ISSUE TITLE
Use Swift package manager instead of importing xcframwork directly for rust FFI

### ISSUE THREAD

**Issue by aki-mizu** [bitcoinppl/cove#65]
Currently it seems the FFI xcframwork is directly embedded inside the iOS project after running build script. 
It makes the iOS project less modular, instead this could be improved by generating a Swift package instead which is how BDK generates it's Swift FFI bindings. The immediate benefit would be when referencing any Cove FFI in any Swift files, you have to import it first, so it becomes more modularized.
An example template could be found here:
https://github.com/thunderbiscuit/uniffi-bindings-template

**Comment by praveenperera** [comment]
No this isn’t a library.
